# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_informatica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['codigo']},
        ),
    ]
